[workspace]
resolver = "2"
members = [
    "charybdis-migrate",
    "charybdis",
    "charybdis-macros",
    "charybdis-parser",
    "examples/actix-web/reddit-api",
    "charybdis_bench",
]

[workspace.lints.clippy]
redundant_clone = "deny"
