[package]
name = "charybdis-migrate"
rust-version = "1.75.0"
version = "0.5.4"
edition = "2021"
description = "Automatic Migration Tool for Charybdis ORM"
repository = "https://github.com/nodecosmos/charybdis"
license = "MIT"
categories = ["database"]

[dependencies]
charybdis_parser = { version = "0.5.4", path = "../charybdis-parser" }
scylla = "0.13.0"
tokio = { version = "1.37.0", features = ["full"] }
serde_json = "1.0.116"
serde = { version = "1.0.20", features = ["derive"] }
colored = "2.1.0"
strip-ansi-escapes = "0.2.0"
clap = { version = "4.5.4", features = ["derive"] }
regex = "1.10.4"

[[bin]]
name = "migrate"
path = "src/migrate.rs"
