[package]
name = "charybdis-migrate"
rust-version = "1.75.0"
version = "0.4.2"
edition = "2021"
description = "Automatic Migration Tool for Charybdis ORM"
repository = "https://github.com/nodecosmos/charybdis"
license = "MIT"

[dependencies]
charybdis_parser = { version = "0.4.2", path = "../charybdis-parser" }
scylla = "0.12.0"
tokio = { version = "1.27.0", features = ["full"] }
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }
colored = "2.0.0"
strip-ansi-escapes = "0.2.0"
clap = { version="4.2.1", features = ["derive"]}
regex = "1.10.1"

[[bin]]
name = "migrate"
path = "src/migrate.rs"
