[package]
name = "charybdis"
rust-version = "1.75.0"
version = "0.4.2"
edition = "2021"
description = "High-Performance ORM for ScyllaDB"
repository = "https://github.com/nodecosmos/charybdis"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charybdis_macros = { version = "0.4.2", path = "../charybdis-macros" }
chrono = { version = "0.4.24", features = ["serde"] }
futures = "0.3.28"
num-bigint = "0.4.3"
scylla = { version = "0.12.0", features = ["full-serialization"] }
tokio = { version = "1.27.0", features = ["full"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }
